# fly.toml app configuration file generated for cjhnt-capitains-nemo-falling-pine-3766 on 2024-04-09T08:51:52+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'cjhnt-capitains-nemo-falling-pine-3766'
primary_region = 'ams'

[build]

[env]
  CORPUS_FOLDERS = 'CJH_Test_Data'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
